# .github/workflows/backup-and-restart.yml
name: Backup and Restart Space
on:
  schedule:
    - cron: '0 4 */2 * *'  # 每2天4点执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  backup-and-restart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
          
      - name: Run backup and restart script
        env:
          WEBDAV_USERNAME: ${{ secrets.WEBDAV_USERNAME }}
          WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
          WEBDAV_URL: ${{ secrets.WEBDAV_URL }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USER: ${{ secrets.HF_USER }}
          HF_SPACE: ${{ secrets.HF_SPACE }}
        run: python restart_space.py
